# Generated by Django 3.0.3 on 2020-02-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0006_merge_20200223_2045'),
        ('users', '0002_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses_taken',
            field=models.ManyToManyField(related_name='students', to='ta_system.Course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ta_assignments',
            field=models.ManyToManyField(related_name='tas', to='ta_system.Course'),
        ),
    ]
