# Generated by Django 3.0.3 on 2020-02-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200225_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eagle_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
