# Generated by Django 3.0.3 on 2020-05-01 23:06

from django.db import migrations, models
import ta_system.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ('-year', 'semester_code')},
        ),
        migrations.AddField(
            model_name='semester',
            name='semester_code',
            field=models.CharField(default='F', help_text="A 1-character semester code, e.g. 'S' for Spring.", max_length=1, validators=[ta_system.validators.DataValidator(message="Please specify a 1-character semester code, e.g. 'F' for Fall.", regex='F|S')], verbose_name='Semester Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.CharField(default='2020', help_text='The year of this semester, e.g. 2020.', max_length=4, validators=[ta_system.validators.DataValidator(message='Please specify the year of this semester, e.g. 2020.', regex='\\d{4}')], verbose_name='Year'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('year', 'semester_code')},
        ),
        migrations.RemoveField(
            model_name='semester',
            name='semester',
        ),
    ]
