# Generated by Django 3.0.3 on 2020-05-14 02:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='course_preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='grad_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='instructor_preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ta_system.Semester', verbose_name='Semester'),
        ),
    ]
