# Generated by Django 3.0.3 on 2020-02-20 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='room',
            new_name='room_number',
        ),
        migrations.RemoveField(
            model_name='coursenumber',
            name='course_code',
        ),
        migrations.AddField(
            model_name='coursenumber',
            name='dept_code',
            field=models.CharField(default='CSCI', max_length=6, verbose_name='Department Code (e.g. CSCI)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_num',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ta_system.CourseNumber', verbose_name='Course Number'),
        ),
        migrations.AlterField(
            model_name='course',
            name='days_of_week',
            field=models.CharField(max_length=10, verbose_name='Days of the Week (e.g. M/W/F)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.TimeField(verbose_name='End Time (e.g. 14:50)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_num_tas',
            field=models.PositiveIntegerField(default=2, verbose_name='Max Number of TAs'),
        ),
        migrations.AlterField(
            model_name='course',
            name='num_tas',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of TAs'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time (e.g. 14:00'),
        ),
        migrations.AlterField(
            model_name='coursenumber',
            name='course_num',
            field=models.CharField(max_length=6, verbose_name='Course Number (e.g. 1101)'),
        ),
        migrations.AlterField(
            model_name='coursenumber',
            name='section_num',
            field=models.CharField(max_length=2, verbose_name='Section Number (e.g. 01)'),
        ),
    ]
