# Generated by Django 3.0.3 on 2020-03-11 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseid',
            options={'verbose_name': 'Course ID', 'verbose_name_plural': 'Course IDs'},
        ),
    ]
