# Generated by Django 3.0.3 on 2020-03-24 01:39

from django.db import migrations, models
import ta_system.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user__last_name',), 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='assigned_tas',
        ),
        migrations.AddField(
            model_name='course',
            name='teaching_assistants',
            field=models.ManyToManyField(blank=True, to='ta_system.Profile', verbose_name='Teaching Assistants'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ta_assignments',
            field=models.ManyToManyField(blank=True, to='ta_system.Course', verbose_name='TA Assignments'),
        ),
        migrations.AlterField(
            model_name='course',
            name='days_of_week',
            field=models.CharField(max_length=13, validators=[ta_system.validators.DataValidator(message="Please specify the days of the week this class meets separatedby slashes, e.g. 'T/R'.", regex='[MTWRFAS](/[MTWRFAS])*')], verbose_name='Days of the Week (e.g. M/W/F)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_num_tas',
            field=models.PositiveIntegerField(default=2, validators=[ta_system.validators.DataValidator(message="Please enter the maximum number of TAs that can be assigned to thiscourse, e.g. '3'. This field defaults to '2'.", regex='\\d+')], verbose_name='Max Number of TAs'),
        ),
        migrations.AlterField(
            model_name='course',
            name='room_number',
            field=models.CharField(max_length=6, validators=[ta_system.validators.DataValidator(message="Please enter the number of the room this class meets in, e.g. '250'.One letter building codes may be included, e.g. '250S'.", regex='\\d+[A-Z]{0,1}')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='courses_taken',
            field=models.ManyToManyField(blank=True, related_name='students', to='ta_system.Course', verbose_name='Courses Taken'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='eagle_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[ta_system.validators.DataValidator(message="Please enter a valid 8-digit eagle id, e.g. '58704254'.", regex='\\d{8}')], verbose_name='Eagle ID'),
        ),
    ]
