# Generated by Django 3.0.3 on 2020-05-02 03:10

from django.db import migrations, models
import django.db.models.deletion
import ta_system.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0002_auto_20200501_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ta_system.Semester', verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_code',
            field=models.CharField(help_text="A 1-character semester code, e.g. 'S' for Spring.", max_length=1, validators=[ta_system.validators.DataValidator(message="Valid semester codes include 'F' for Fall and 'S' for Spring.", regex='F|S')], verbose_name='Semester Code'),
        ),
    ]
