# Generated by Django 3.0.2 on 2020-05-18 20:53

from django.db import migrations, models
import ta_system.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0002_auto_20200513_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='building',
            field=models.CharField(help_text='The building this class meets in, e.g. Fulton.', max_length=30, validators=[ta_system.validators.DataValidator(message="Please enter the building this class meets in, e.g. 'Fulton'.", regex='.*')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=60, validators=[ta_system.validators.DataValidator(message="Please enter the name of the course, e.g. 'Computer Science I'.", regex='.+')]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(help_text='The name of this instructor.', max_length=60, unique=True, validators=[ta_system.validators.DataValidator(message="Please enter the name of the Instructor, e.g. 'Robert Muller'.", regex='.+')], verbose_name='Instructor'),
        ),
    ]
