# Generated by Django 3.0.3 on 2020-02-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0002_auto_20200220_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='instructor',
            name='name',
            field=models.CharField(default='Sample', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_num',
            field=models.CharField(max_length=14, unique=True, verbose_name='Course Number'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time (e.g. 14:00)'),
        ),
    ]
