# Generated by Django 3.0.3 on 2020-04-03 00:28

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0002_profile_lab_hour_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lab_hour_preferences',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
