# Generated by Django 3.0.3 on 2020-03-11 00:43

from django.db import migrations, models
import ta_system.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0002_auto_20200310_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseid',
            name='course_number',
            field=models.CharField(max_length=10, validators=[ta_system.validators.DataValidator(message="Please enter a valid full course number, e.g. 'CSCI110101'.", regex='[A-Z]{4}\\d{6}')], verbose_name='Course Number (e.g. CSCI110101)'),
        ),
    ]
