# Generated by Django 3.0.3 on 2020-05-03 04:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0003_auto_20200501_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='lab_hour_assignments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
