# Generated by Django 3.0.2 on 2020-05-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0003_auto_20200504_1938'),
        ('ta_system', '0002_semester_lab_hour_constraints'),
    ]

    operations = [
    ]
