# Generated by Django 3.0.3 on 2020-02-21 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0003_auto_20200220_1944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseNumber',
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ta_system.Instructor'),
        ),
    ]
