# Generated by Django 3.0.3 on 2020-05-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0004_semester_lab_hour_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_blacklisted',
            field=models.BooleanField(default=False, help_text='If a student is blacklisted, the simulation will not assign her to be a TA.', verbose_name='Is Blacklisted'),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='max_num_lab_hours_per_ta',
            field=models.PositiveIntegerField(default=3, help_text='When the simulation is run, students will not be assigned more hours in the lab than this maximum value.', verbose_name='Maximum Number of Lab Hours per TA'),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='status',
            field=models.BooleanField(default=False, help_text='When the system is closed, students will not be able to submit applications.', verbose_name='Is Open'),
        ),
    ]
