# Generated by Django 3.0.3 on 2020-05-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0005_auto_20200508_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemstatus',
            name='max_num_lab_hours_per_ta',
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='max_lab_hours_per_ta',
            field=models.PositiveIntegerField(default=3, help_text='When the simulation is run, students will not be assigned more hours in the CS lab than this maximum value.', verbose_name='Max Lab Hours per TA'),
        ),
    ]
