# Generated by Django 3.0.3 on 2020-02-24 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0005_auto_20200223_2034'),
        ('ta_system', '0005_auto_20200223_1927'),
    ]

    operations = [
    ]
