# Generated by Django 3.0.3 on 2020-03-11 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0005_auto_20200310_2110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('semester', 'course_number')},
        ),
    ]
