# Generated by Django 3.0.3 on 2020-02-26 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ta_system', '0006_merge_20200223_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eagle_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('courses_taken', models.ManyToManyField(blank=True, related_name='students', to='ta_system.Course')),
                ('ta_assignments', models.ManyToManyField(blank=True, related_name='tas', to='ta_system.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
