# Generated by Django 3.0.3 on 2020-05-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0006_auto_20200508_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_blacklisted',
            field=models.BooleanField(default=False, help_text='If a student is blacklisted, the simulation will not assign her to be a TA. This does not affect manual TA assignments.', verbose_name='Is Blacklisted'),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='max_lab_hours_per_ta',
            field=models.PositiveIntegerField(default=3, help_text='When the simulation is run, students will not be assigned more hours in the CS lab than this maximum value. This does not affect manual lab hour assignments.', verbose_name='Max Lab Hours per TA'),
        ),
    ]
