# Generated by Django 3.0.3 on 2020-04-03 03:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0006_auto_20200402_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lab_hour_preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
