# Generated by Django 3.0.3 on 2020-03-17 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0006_auto_20200311_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('semester', 'course_number')},
        ),
    ]
