# Generated by Django 3.0.3 on 2020-03-20 02:42

from django.db import migrations, models
import ta_system.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0007_auto_20200317_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user__last_name',), 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='profile',
            name='ta_assignments',
            field=models.ManyToManyField(blank=True, to='ta_system.Course', verbose_name='TA Assignments'),
        ),
        migrations.AlterField(
            model_name='course',
            name='assigned_tas',
            field=models.ManyToManyField(blank=True, to='ta_system.Profile', verbose_name='Assigned TAs'),
        ),
        migrations.AlterField(
            model_name='course',
            name='days_of_week',
            field=models.CharField(max_length=13, validators=[ta_system.validators.DataValidator(message="Please specify the days of the week this class meets separated by slashes, e.g. 'T/R'.", regex='[MTWRFAS](/[MTWRFAS])*')], verbose_name='Days of the Week (e.g. M/W/F)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='courses_taken',
            field=models.ManyToManyField(blank=True, related_name='students', to='ta_system.Course', verbose_name='Courses Taken'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='eagle_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[ta_system.validators.DataValidator(message="Please enter a valid 8-digit eagle id, e.g. '58704254'.", regex='\\d{8}')], verbose_name='Eagle ID'),
        ),
    ]
