# Generated by Django 3.0.3 on 2020-04-05 19:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0007_auto_20200402_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lab_hour_preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
