# Generated by Django 3.0.3 on 2020-03-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0008_auto_20200319_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assigned_tas',
        ),
        migrations.AddField(
            model_name='course',
            name='teaching_assistants',
            field=models.ManyToManyField(blank=True, to='ta_system.Profile', verbose_name='Teaching Assistants'),
        ),
    ]
