# Generated by Django 3.0.3 on 2020-03-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0009_auto_20200225_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_num',
            new_name='course_number',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
