# Generated by Django 3.0.3 on 2020-03-24 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_system', '0011_auto_20200321_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ('-semester',)},
        ),
    ]
